/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AppRouteImport } from './routes/app'
import { Route as BookRouteImport } from './routes/book'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CookiesRouteImport } from './routes/cookies'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as FeaturesRouteImport } from './routes/features'
import { Route as GlossaryRouteImport } from './routes/glossary'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as IntegrationsRouteImport } from './routes/integrations'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ProductRouteImport } from './routes/product'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as SecurityRouteImport } from './routes/security'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as TrialRouteImport } from './routes/trial'
import { Route as UnsubscribeRouteImport } from './routes/unsubscribe'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminArticlesRouteImport } from './routes/admin/articles'
import { Route as AdminInboxRouteImport } from './routes/admin/inbox'
import { Route as AdminLeadsRouteImport } from './routes/admin/leads'
import { Route as AdminSiteRouteImport } from './routes/admin/site'
import { Route as AdminWriteRouteImport } from './routes/admin/write'
import { Route as BlogIndexRouteImport } from './routes/blog/index'
import { Route as BlogSlugRouteImport } from './routes/blog/$slug'
import { Route as CompareIndexRouteImport } from './routes/compare/index'
import { Route as CompareBirdeyeAlternativeRouteImport } from './routes/compare/birdeye-alternative'
import { Route as CompareBrightlocalAlternativeRouteImport } from './routes/compare/brightlocal-alternative'
import { Route as CompareMozLocalAlternativeRouteImport } from './routes/compare/moz-local-alternative'
import { Route as CompareUberallAlternativeRouteImport } from './routes/compare/uberall-alternative'
import { Route as CompareYextAlternativeRouteImport } from './routes/compare/yext-alternative'
import { Route as ToolsListingOpsRoiEngineRouteImport } from './routes/tools/listing-ops-roi-engine'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const BookRoute = BookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiesRoute = CookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesRoute = FeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => rootRouteImport,
} as any)
const GlossaryRoute = GlossaryRouteImport.update({
  id: '/glossary',
  path: '/glossary',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegrationsRoute = IntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductRoute = ProductRouteImport.update({
  id: '/product',
  path: '/product',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const SecurityRoute = SecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const TrialRoute = TrialRouteImport.update({
  id: '/trial',
  path: '/trial',
  getParentRoute: () => rootRouteImport,
} as any)
const UnsubscribeRoute = UnsubscribeRouteImport.update({
  id: '/unsubscribe',
  path: '/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminArticlesRoute = AdminArticlesRouteImport.update({
  id: '/admin/articles',
  path: '/admin/articles',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminInboxRoute = AdminInboxRouteImport.update({
  id: '/admin/inbox',
  path: '/admin/inbox',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLeadsRoute = AdminLeadsRouteImport.update({
  id: '/admin/leads',
  path: '/admin/leads',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSiteRoute = AdminSiteRouteImport.update({
  id: '/admin/site',
  path: '/admin/site',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminWriteRoute = AdminWriteRouteImport.update({
  id: '/admin/write',
  path: '/admin/write',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareIndexRoute = CompareIndexRouteImport.update({
  id: '/compare/',
  path: '/compare/',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareBirdeyeAlternativeRoute =
  CompareBirdeyeAlternativeRouteImport.update({
    id: '/compare/birdeye-alternative',
    path: '/compare/birdeye-alternative',
    getParentRoute: () => rootRouteImport,
  } as any)
const CompareBrightlocalAlternativeRoute =
  CompareBrightlocalAlternativeRouteImport.update({
    id: '/compare/brightlocal-alternative',
    path: '/compare/brightlocal-alternative',
    getParentRoute: () => rootRouteImport,
  } as any)
const CompareMozLocalAlternativeRoute =
  CompareMozLocalAlternativeRouteImport.update({
    id: '/compare/moz-local-alternative',
    path: '/compare/moz-local-alternative',
    getParentRoute: () => rootRouteImport,
  } as any)
const CompareUberallAlternativeRoute =
  CompareUberallAlternativeRouteImport.update({
    id: '/compare/uberall-alternative',
    path: '/compare/uberall-alternative',
    getParentRoute: () => rootRouteImport,
  } as any)
const CompareYextAlternativeRoute = CompareYextAlternativeRouteImport.update({
  id: '/compare/yext-alternative',
  path: '/compare/yext-alternative',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsListingOpsRoiEngineRoute =
  ToolsListingOpsRoiEngineRouteImport.update({
    id: '/tools/listing-ops-roi-engine',
    path: '/tools/listing-ops-roi-engine',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/app': typeof AppRoute
  '/book': typeof BookRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/demo': typeof DemoRoute
  '/features': typeof FeaturesRoute
  '/glossary': typeof GlossaryRoute
  '/how-it-works': typeof HowItWorksRoute
  '/integrations': typeof IntegrationsRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/product': typeof ProductRoute
  '/resources': typeof ResourcesRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/security': typeof SecurityRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/trial': typeof TrialRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/admin/articles': typeof AdminArticlesRoute
  '/admin/inbox': typeof AdminInboxRoute
  '/admin/leads': typeof AdminLeadsRoute
  '/admin/site': typeof AdminSiteRoute
  '/admin/write': typeof AdminWriteRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/compare/birdeye-alternative': typeof CompareBirdeyeAlternativeRoute
  '/compare/brightlocal-alternative': typeof CompareBrightlocalAlternativeRoute
  '/compare/moz-local-alternative': typeof CompareMozLocalAlternativeRoute
  '/compare/uberall-alternative': typeof CompareUberallAlternativeRoute
  '/compare/yext-alternative': typeof CompareYextAlternativeRoute
  '/tools/listing-ops-roi-engine': typeof ToolsListingOpsRoiEngineRoute
  '/admin/': typeof AdminIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/compare/': typeof CompareIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/app': typeof AppRoute
  '/book': typeof BookRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/demo': typeof DemoRoute
  '/features': typeof FeaturesRoute
  '/glossary': typeof GlossaryRoute
  '/how-it-works': typeof HowItWorksRoute
  '/integrations': typeof IntegrationsRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/product': typeof ProductRoute
  '/resources': typeof ResourcesRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/security': typeof SecurityRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/trial': typeof TrialRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/admin/articles': typeof AdminArticlesRoute
  '/admin/inbox': typeof AdminInboxRoute
  '/admin/leads': typeof AdminLeadsRoute
  '/admin/site': typeof AdminSiteRoute
  '/admin/write': typeof AdminWriteRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/compare/birdeye-alternative': typeof CompareBirdeyeAlternativeRoute
  '/compare/brightlocal-alternative': typeof CompareBrightlocalAlternativeRoute
  '/compare/moz-local-alternative': typeof CompareMozLocalAlternativeRoute
  '/compare/uberall-alternative': typeof CompareUberallAlternativeRoute
  '/compare/yext-alternative': typeof CompareYextAlternativeRoute
  '/tools/listing-ops-roi-engine': typeof ToolsListingOpsRoiEngineRoute
  '/admin': typeof AdminIndexRoute
  '/blog': typeof BlogIndexRoute
  '/compare': typeof CompareIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/app': typeof AppRoute
  '/book': typeof BookRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/demo': typeof DemoRoute
  '/features': typeof FeaturesRoute
  '/glossary': typeof GlossaryRoute
  '/how-it-works': typeof HowItWorksRoute
  '/integrations': typeof IntegrationsRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/product': typeof ProductRoute
  '/resources': typeof ResourcesRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/security': typeof SecurityRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/trial': typeof TrialRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/admin/articles': typeof AdminArticlesRoute
  '/admin/inbox': typeof AdminInboxRoute
  '/admin/leads': typeof AdminLeadsRoute
  '/admin/site': typeof AdminSiteRoute
  '/admin/write': typeof AdminWriteRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/compare/birdeye-alternative': typeof CompareBirdeyeAlternativeRoute
  '/compare/brightlocal-alternative': typeof CompareBrightlocalAlternativeRoute
  '/compare/moz-local-alternative': typeof CompareMozLocalAlternativeRoute
  '/compare/uberall-alternative': typeof CompareUberallAlternativeRoute
  '/compare/yext-alternative': typeof CompareYextAlternativeRoute
  '/tools/listing-ops-roi-engine': typeof ToolsListingOpsRoiEngineRoute
  '/admin/': typeof AdminIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/compare/': typeof CompareIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/app'
    | '/book'
    | '/contact'
    | '/cookies'
    | '/demo'
    | '/features'
    | '/glossary'
    | '/how-it-works'
    | '/integrations'
    | '/login'
    | '/pricing'
    | '/privacy'
    | '/product'
    | '/resources'
    | '/robots.txt'
    | '/security'
    | '/signup'
    | '/sitemap.xml'
    | '/terms'
    | '/trial'
    | '/unsubscribe'
    | '/admin/articles'
    | '/admin/inbox'
    | '/admin/leads'
    | '/admin/site'
    | '/admin/write'
    | '/blog/$slug'
    | '/compare/birdeye-alternative'
    | '/compare/brightlocal-alternative'
    | '/compare/moz-local-alternative'
    | '/compare/uberall-alternative'
    | '/compare/yext-alternative'
    | '/tools/listing-ops-roi-engine'
    | '/admin/'
    | '/blog/'
    | '/compare/'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/app'
    | '/book'
    | '/contact'
    | '/cookies'
    | '/demo'
    | '/features'
    | '/glossary'
    | '/how-it-works'
    | '/integrations'
    | '/login'
    | '/pricing'
    | '/privacy'
    | '/product'
    | '/resources'
    | '/robots.txt'
    | '/security'
    | '/signup'
    | '/sitemap.xml'
    | '/terms'
    | '/trial'
    | '/unsubscribe'
    | '/admin/articles'
    | '/admin/inbox'
    | '/admin/leads'
    | '/admin/site'
    | '/admin/write'
    | '/blog/$slug'
    | '/compare/birdeye-alternative'
    | '/compare/brightlocal-alternative'
    | '/compare/moz-local-alternative'
    | '/compare/uberall-alternative'
    | '/compare/yext-alternative'
    | '/tools/listing-ops-roi-engine'
    | '/admin'
    | '/blog'
    | '/compare'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/app'
    | '/book'
    | '/contact'
    | '/cookies'
    | '/demo'
    | '/features'
    | '/glossary'
    | '/how-it-works'
    | '/integrations'
    | '/login'
    | '/pricing'
    | '/privacy'
    | '/product'
    | '/resources'
    | '/robots.txt'
    | '/security'
    | '/signup'
    | '/sitemap.xml'
    | '/terms'
    | '/trial'
    | '/unsubscribe'
    | '/admin/articles'
    | '/admin/inbox'
    | '/admin/leads'
    | '/admin/site'
    | '/admin/write'
    | '/blog/$slug'
    | '/compare/birdeye-alternative'
    | '/compare/brightlocal-alternative'
    | '/compare/moz-local-alternative'
    | '/compare/uberall-alternative'
    | '/compare/yext-alternative'
    | '/tools/listing-ops-roi-engine'
    | '/admin/'
    | '/blog/'
    | '/compare/'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AppRoute: typeof AppRoute
  BookRoute: typeof BookRoute
  ContactRoute: typeof ContactRoute
  CookiesRoute: typeof CookiesRoute
  DemoRoute: typeof DemoRoute
  FeaturesRoute: typeof FeaturesRoute
  GlossaryRoute: typeof GlossaryRoute
  HowItWorksRoute: typeof HowItWorksRoute
  IntegrationsRoute: typeof IntegrationsRoute
  LoginRoute: typeof LoginRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  ProductRoute: typeof ProductRoute
  ResourcesRoute: typeof ResourcesRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SecurityRoute: typeof SecurityRoute
  SignupRoute: typeof SignupRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  TrialRoute: typeof TrialRoute
  UnsubscribeRoute: typeof UnsubscribeRoute
  AdminArticlesRoute: typeof AdminArticlesRoute
  AdminInboxRoute: typeof AdminInboxRoute
  AdminLeadsRoute: typeof AdminLeadsRoute
  AdminSiteRoute: typeof AdminSiteRoute
  AdminWriteRoute: typeof AdminWriteRoute
  BlogSlugRoute: typeof BlogSlugRoute
  CompareBirdeyeAlternativeRoute: typeof CompareBirdeyeAlternativeRoute
  CompareBrightlocalAlternativeRoute: typeof CompareBrightlocalAlternativeRoute
  CompareMozLocalAlternativeRoute: typeof CompareMozLocalAlternativeRoute
  CompareUberallAlternativeRoute: typeof CompareUberallAlternativeRoute
  CompareYextAlternativeRoute: typeof CompareYextAlternativeRoute
  ToolsListingOpsRoiEngineRoute: typeof ToolsListingOpsRoiEngineRoute
  AdminIndexRoute: typeof AdminIndexRoute
  BlogIndexRoute: typeof BlogIndexRoute
  CompareIndexRoute: typeof CompareIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book': {
      id: '/book'
      path: '/book'
      fullPath: '/book'
      preLoaderRoute: typeof BookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookies': {
      id: '/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof CookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features': {
      id: '/features'
      path: '/features'
      fullPath: '/features'
      preLoaderRoute: typeof FeaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/glossary': {
      id: '/glossary'
      path: '/glossary'
      fullPath: '/glossary'
      preLoaderRoute: typeof GlossaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integrations': {
      id: '/integrations'
      path: '/integrations'
      fullPath: '/integrations'
      preLoaderRoute: typeof IntegrationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product': {
      id: '/product'
      path: '/product'
      fullPath: '/product'
      preLoaderRoute: typeof ProductRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/security': {
      id: '/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof SecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trial': {
      id: '/trial'
      path: '/trial'
      fullPath: '/trial'
      preLoaderRoute: typeof TrialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/unsubscribe': {
      id: '/unsubscribe'
      path: '/unsubscribe'
      fullPath: '/unsubscribe'
      preLoaderRoute: typeof UnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/articles': {
      id: '/admin/articles'
      path: '/admin/articles'
      fullPath: '/admin/articles'
      preLoaderRoute: typeof AdminArticlesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/inbox': {
      id: '/admin/inbox'
      path: '/admin/inbox'
      fullPath: '/admin/inbox'
      preLoaderRoute: typeof AdminInboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/leads': {
      id: '/admin/leads'
      path: '/admin/leads'
      fullPath: '/admin/leads'
      preLoaderRoute: typeof AdminLeadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/site': {
      id: '/admin/site'
      path: '/admin/site'
      fullPath: '/admin/site'
      preLoaderRoute: typeof AdminSiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/write': {
      id: '/admin/write'
      path: '/admin/write'
      fullPath: '/admin/write'
      preLoaderRoute: typeof AdminWriteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare/': {
      id: '/compare/'
      path: '/compare'
      fullPath: '/compare/'
      preLoaderRoute: typeof CompareIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare/birdeye-alternative': {
      id: '/compare/birdeye-alternative'
      path: '/compare/birdeye-alternative'
      fullPath: '/compare/birdeye-alternative'
      preLoaderRoute: typeof CompareBirdeyeAlternativeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare/brightlocal-alternative': {
      id: '/compare/brightlocal-alternative'
      path: '/compare/brightlocal-alternative'
      fullPath: '/compare/brightlocal-alternative'
      preLoaderRoute: typeof CompareBrightlocalAlternativeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare/moz-local-alternative': {
      id: '/compare/moz-local-alternative'
      path: '/compare/moz-local-alternative'
      fullPath: '/compare/moz-local-alternative'
      preLoaderRoute: typeof CompareMozLocalAlternativeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare/uberall-alternative': {
      id: '/compare/uberall-alternative'
      path: '/compare/uberall-alternative'
      fullPath: '/compare/uberall-alternative'
      preLoaderRoute: typeof CompareUberallAlternativeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare/yext-alternative': {
      id: '/compare/yext-alternative'
      path: '/compare/yext-alternative'
      fullPath: '/compare/yext-alternative'
      preLoaderRoute: typeof CompareYextAlternativeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/listing-ops-roi-engine': {
      id: '/tools/listing-ops-roi-engine'
      path: '/tools/listing-ops-roi-engine'
      fullPath: '/tools/listing-ops-roi-engine'
      preLoaderRoute: typeof ToolsListingOpsRoiEngineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AppRoute: AppRoute,
  BookRoute: BookRoute,
  ContactRoute: ContactRoute,
  CookiesRoute: CookiesRoute,
  DemoRoute: DemoRoute,
  FeaturesRoute: FeaturesRoute,
  GlossaryRoute: GlossaryRoute,
  HowItWorksRoute: HowItWorksRoute,
  IntegrationsRoute: IntegrationsRoute,
  LoginRoute: LoginRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  ProductRoute: ProductRoute,
  ResourcesRoute: ResourcesRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SecurityRoute: SecurityRoute,
  SignupRoute: SignupRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  TrialRoute: TrialRoute,
  UnsubscribeRoute: UnsubscribeRoute,
  AdminArticlesRoute: AdminArticlesRoute,
  AdminInboxRoute: AdminInboxRoute,
  AdminLeadsRoute: AdminLeadsRoute,
  AdminSiteRoute: AdminSiteRoute,
  AdminWriteRoute: AdminWriteRoute,
  BlogSlugRoute: BlogSlugRoute,
  CompareBirdeyeAlternativeRoute: CompareBirdeyeAlternativeRoute,
  CompareBrightlocalAlternativeRoute: CompareBrightlocalAlternativeRoute,
  CompareMozLocalAlternativeRoute: CompareMozLocalAlternativeRoute,
  CompareUberallAlternativeRoute: CompareUberallAlternativeRoute,
  CompareYextAlternativeRoute: CompareYextAlternativeRoute,
  ToolsListingOpsRoiEngineRoute: ToolsListingOpsRoiEngineRoute,
  AdminIndexRoute: AdminIndexRoute,
  BlogIndexRoute: BlogIndexRoute,
  CompareIndexRoute: CompareIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
